name: Deploy to GitHub Pages

on:
  push:
    branches: [master]  # Sử dụng branch master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install lightningcss
        run: npm install lightningcss

      - name: Build project
        run: npm run build
        env:
          LIGHTNINGCSS_TARGET_ENV: nodejs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out