name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [master]   # đổi thành main nếu repo dùng main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (clean)
        run: npm ci

      # ÉP cài đúng binary native cho Linux + pin phiên bản để tránh lệch
      - name: Pin and install Tailwind v4 native toolchain
        run: |
          # Pin versions (bạn có thể điều chỉnh, nhưng 1.25.x hiện rất phổ biến)
          npm i -D @tailwindcss/oxide@^4 @tailwindcss/postcss@^4 lightningcss@^1.25.1 lightningcss-linux-x64-gnu@^1.25.1
          # Rebuild để link đúng binary
          npm rebuild lightningcss

      - name: Probe native bindings (debug)
        run: |
          node -e "require('@tailwindcss/oxide'); console.log('✅ oxide native OK')"
          node -e "require('lightningcss'); console.log('✅ lightningcss native OK')"

      # (Tùy chọn) Nếu muốn fallback WASM khi native lỗi, bỏ comment 2 step dưới:
      # - name: Fallback to WASM (if needed)
      #   if: failure()
      #   run: |
      #     npm i -D lightningcss-wasm @tailwindcss/oxide-wasm
      #     echo 'LIGHTNINGCSS_FORCE_WASM=1' >> $GITHUB_ENV
      #     echo 'TAILWIND_DISABLE_OXIDE=1' >> $GITHUB_ENV

      - name: Build (Next export -> out/)
        run: npm run build
        env:
          # Giữ target env cho lightningcss
          LIGHTNINGCSS_TARGET_ENV: nodejs

      - name: Verify out/
        run: test -d out && ls -la out

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
