name: Deploy demo (Vercel Preview)

on:
  push:
    branches: [ demo ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Deploy to Vercel (preview)
        id: vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm i -g vercel@latest
          vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
          URL=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN --yes)
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Preview URL: $URL"

      # Alias về 1 subdomain cố định cho nhánh demo (tuỳ chọn)
      - name: Alias to demo domain
        if: steps.vercel.outputs.url != ''
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel alias set ${{ steps.vercel.outputs.url }} demo-yourapp.vercel.app --token=$VERCEL_TOKEN
